/*
    Problem: Find the Difference

    Description:

    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Example 1:

    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Example 2:

    Input: s = "", t = "y"
    Output: "y"
*/

impl Solution {
    pub fn find_the_difference(s: String, t: String) -> char {
        let mut result: u8 = 0;

        for b in s.bytes() {
            result ^= b;
        }

        for b in t.bytes() {
            result ^= b;
        }

        result as char
    }
}
